<a href="https://colab.research.google.com/github/Varshas-324/Main-project/blob/main/Copy_of_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

LISTS

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [ ]:
import numpy as np
np1 = np.random.rand(3)
np1

array([0.80877916, 0.11011644, 0.71302556])

In [ ]:
np1.dtype

dtype('float64')

TENSORS

In [ ]:
import torch
tensor_2d = torch.rand(3,4)
tensor_2d
#tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
##create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([0.8088, 0.1101, 0.7130], dtype=torch.float64)